#!/bin/bash

npm install
npm update
node generateMessaging.js
node generateTimezones.js
node generateTranslations.js
source scripts/native2ascii
grunt build
mvn clean package deploy -U
mvn package
java -jar target/cui-i18n-1.0.13.jar -cp com.covisint.cui.i18n ListCountry
